// <auto-generated />
using System;
using Creating.From.ConsoleApp.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Creating.From.ConsoleApp.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20190206122639_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Creating.From.ConsoleApp.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("64c3d8f1-723f-4a05-a8a6-af6329ea5781"),
                            Name = "Santiago Posteguillo"
                        },
                        new
                        {
                            Id = new Guid("8ef6815b-ebf8-4f2f-b25f-fd7530025723"),
                            Name = "Simon Scarrow"
                        },
                        new
                        {
                            Id = new Guid("b343ac23-0e8d-4abf-88a0-7beacaf8caff"),
                            Name = "Steven Pressfiel"
                        },
                        new
                        {
                            Id = new Guid("b3dbb82a-5387-466a-a99d-4b9d83903bdb"),
                            Name = "Orson Scott"
                        },
                        new
                        {
                            Id = new Guid("7aba4e5e-309a-49b7-a8f4-f5fb64ad09cd"),
                            Name = "John Scalzi"
                        });
                });

            modelBuilder.Entity("Creating.From.ConsoleApp.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AuthorId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3c64f20-e40e-437c-8952-b6dab6b4513a"),
                            AuthorId = new Guid("64c3d8f1-723f-4a05-a8a6-af6329ea5781"),
                            Name = "Africanus"
                        },
                        new
                        {
                            Id = new Guid("41fad579-629f-49ff-855e-36b88cf29cb9"),
                            AuthorId = new Guid("64c3d8f1-723f-4a05-a8a6-af6329ea5781"),
                            Name = "Las legiones malditas"
                        });
                });

            modelBuilder.Entity("Creating.From.ConsoleApp.Entities.Book", b =>
                {
                    b.HasOne("Creating.From.ConsoleApp.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
